apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewship-backend
spec:
  selector:
    matchLabels:
      app: crewship-backend
      component: crewship-backend
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: crewship-backend
        component: crewship-backend
        tier: back
    spec:
      containers:
        - name: crewship-backend
          image: phjppo0918/crewship-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DATABASE_MASTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.username
            - name: DATABASE_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.password
            - name: DATABASE_MASTER_URL
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.url
            - name: DATABASE_MASTER_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.schema
            - name: DATABASE_SLAVE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.slave.username
            - name: DATABASE_SLAVE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.slave.password
            - name: DATABASE_SLAVE_URL
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.slave.url
            - name: DATABASE_SLAVE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.slave.schema

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: redis.host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: redis.port

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: google.client.id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: google.client.secret
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: kakao.client.id
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: naver.client.id
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: naver.client.secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: jwt.secret
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: crewship-server-secret
                  key: client.url
            - name: CLIENT_ENDPOINT
              value: TeamList