apiVersion: v1
kind: Service
metadata:
  name: crewship-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: crewship-backend
    component: crewship-backend
    tier: back