apiVersion: v1
kind: Service
metadata:
  name: owl-forest-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: owl-forest-backend
    component: owl-forest-backend
    tier: back