apiVersion: v1
kind: Service
metadata:
  name: owl-forest-backend-dev
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30505
  selector:
    app: owl-forest-backend-dev
    component: owl-forest-backend-dev
    tier: back