apiVersion: apps/v1
kind: Deployment
metadata:
  name: myway-frontend
  labels:
    app: myway-frontend
    tier: front
spec:
  selector:
    matchLabels:
      app: myway-frontend
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: myway-frontend
        tier: front
    spec:
      containers:
        - name: myway-frontend
          image: phjppo0918/myway-frontend:latest
          imagePullPolicy: Always
          # env:
          #   - name: SERVER_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: server-secret
          #         key: server.url
          #   - name: SERVER_PORT
          #     valueFrom:
          #       secretKeyRef:
          #         name: server-secret
          #         key: server.port
          ports:
            - containerPort: 80
