apiVersion: v1
kind: Service
metadata:
  name: myway-frontend
spec:
  type: NodePort
  selector:
    app: myway-frontend
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30123
