apiVersion: v1
kind: Service
metadata:
  name: crewship-frontend
spec:
  type: NodePort
  selector:
    app: crewship-frontend
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30123
