name: frontend - feat
on: 
  branches: 
    - front/feat/**
    - front/feature/**
    - frontend/feat/**
    - frontend/feature/**
  
defaults:
  run:
    shell: bash
    working-directory: ./frontend