name: frontend - main
on:
  branches:
    - front/main/**
    - front/release/**
    - front/hotfix/**
    - frontend/main/**
    - frontend/release/**
    - frontend/hotfix/**

defaults:
  run:
    shell: bash
    working-directory: ./frontend
