apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewship-mysql-dev
spec:
  selector:
    matchLabels:
      app: crewship-mysql-dev
      component: crewship-mysql-dev
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: crewship-mysql-dev
        component: crewship-mysql-dev
        tier: back
    spec:
      containers:
        - name: crewship-mysql-dev
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: crewship-database-secret
                  key: database.master.schema