apiVersion: v1
kind: Service
metadata:
  name: crewship-mysql-dev
spec:
  ports:
    - name: crewship-mysql-dev
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: crewship-mysql-dev
    component: crewship-mysql-dev
  clusterIP: None