name: backend - build docker image
defaults:
  run:
    shell: bash
    working-directory: ./back
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - run: gradle build
      - run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BACK_IMAGE_NAME }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BACK_IMAGE_NAME }}

