name: backend - main
on:
  push:
    branches:
      - back/main/**
      - backend/main/**
defaults:
  run:
    shell: bash
    working-directory: ./back
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pr into main"
