name: backend - feat
on: 
  push: 
    branches: 
      - back/feat/**
      - back/feature/**
      - backend/feat/**
      - backend/feature/**
  pull_request: 
    branches: 
      - back/feat/**
      - back/feature/**
      - backend/feat/**
      - backend/feature/**
defaults:
  run:
    shell: bash
    working-directory: ./back
jobs:
  integration-test:
    uses: ./.github/workflows/back-integration-test.yml
  replace-google-format:
    uses: ./.github/workflows/reformat-google-java-convenction.yml
