name: build and push backend docker image
on: 
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ./back

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - run: gradle test