name: build and push frontend docker image
on: 
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ./front

jobs:
   build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v3

      - run: |
          npm install yarn
          yarn build
      - run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONT_IMAGE_NAME }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONT_IMAGE_NAME }}