name: cd - dev 
on:
  push:
    branches:
      - "main"
      - "dev"
      - "develop"

defaults:
  run:
    shell: bash
    working-directory: ./k8s

jobs:
  build-and-deploy-back-docker-img:
    name: Deploy-back
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-back-docker-img.yml
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
   
          
  build-and-deploy-front-docker-img:
    name: Deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-front-docker-img.yml
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_FRONT_IMAGE_NAME: ${{ secrets.DOCKER_FRONT_IMAGE_NAME }}
   
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      - run: |
          kubectl delete secret database-secret
          kubectl create secret generic database-secret \
            --from-literal=server=1234 \
            --from-literal=server=1234 \
      - run: |
          kubectl delete svc myway-frontend
          kubectl delete deploy myway-frontend
          kubectl apply -k ./frontend    