name: frontend - feat
on: 
  push:
    branches: 
      - front/feat/**
      - front/feature/**
      - frontend/feat/**
      - frontend/feature/**
  
defaults:
  run:
    shell: bash
    working-directory: ./frontend
    
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "frontend into feat"