name: frontend - dev
on: 
  push: 
    branches:
      - front/dev/**
      - front/develop/** 
      - frontend/dev/**
      - frontend/develop/**
  
defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "frontend into dev"